using System;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using Avtorentovik.Core.Model;
using Avtorentovik.Forms;
using Avtorentovik.Properties;
using Avtorentovik.Utils;

namespace Avtorentovik
{
    public partial class LoginForm : Form
    {
        private User _currentUser;

        public LoginForm()
        {
            InitializeComponent();
            try
            {
                var autogeneratedHelper = typeof(Core.DB.ConnectionHelper);
                const string constName = nameof(Model.ConnectionString);
                if (autogeneratedHelper.GetField(constName) != null)
                    throw new ApplicationException(
                        $"Duplicated {constName}! Please review {autogeneratedHelper.FullName}");

                Model.Init();
            }
            catch (Exception ex)
            {
                VLog.Log(ex);
                MessageBox.Show(ex.Message);                                
            }
        }

        private void buttonLogin_Click(object sender, EventArgs e)
        {
            try
            {
                Login();
            }
            catch (Exception ex)
            {                
               VLog.Log(ex);
                MessageBox.Show(ex.Message);
            }
            
        }

        private void Login()
        {
            var login = textBoxLogin.Text.Trim();            
            var pass = MD5Hash.Get(textBoxPassword.Text.Trim(), Encoding.Default);
            var users = Model.Users.GetAll();
            _currentUser = users.FirstOrDefault(q => q.Login == login && q.PasswordHash == pass);
            if (_currentUser == null)
            {
                _currentUser = users.FirstOrDefault(q => q.Login == login);
                if (_currentUser != null)
                {
                    MessageBox.Show(Resources.LoginForm_Login_Не_правильно_введен_пароль_, Resources.LoginForm_Login_Внимание);
                    return;
                }

                if (MessageBox.Show(Resources.LoginForm_Login_Такого_пользователя_нет__Хотите_создать_нового_,
                        Resources.LoginForm_Login_Внимание, MessageBoxButtons.YesNo) == DialogResult.No)
                    return;
                var uf = new UserForm();
                uf.ShowDialog();
                return;
            }
            _currentUser.Password = textBoxPassword.Text.Trim();
            var mf = new MainForm(_currentUser, this);
            Hide();
            mf.Show();
        }

        public void ShowLogin()
        {
            //textBoxLogin.Text = "Admin";
            textBoxPassword.Text = "";
            Show();
        }
    }
}
