//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtorentovik.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avtorentovik.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такая модель уже есть..
        /// </summary>
        internal static string CarModels_AddNew_Такая_модель_уже_есть_ {
            get {
                return ResourceManager.GetString("CarModels_AddNew_Такая_модель_уже_есть_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель не найдена..
        /// </summary>
        internal static string CarModels_Read_Модель_не_найдена_ {
            get {
                return ResourceManager.GetString("CarModels_Read_Модель_не_найдена_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка выдачи не найдена..
        /// </summary>
        internal static string CarRentals_Read_Точка_выдачи_не_найдена_ {
            get {
                return ResourceManager.GetString("CarRentals_Read_Точка_выдачи_не_найдена_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автомобиль не найден..
        /// </summary>
        internal static string Cars_Read_Автомобиль_не_найден_ {
            get {
                return ResourceManager.GetString("Cars_Read_Автомобиль_не_найден_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент не найден..
        /// </summary>
        internal static string Clients_Read_Клиент_не_найден_ {
            get {
                return ResourceManager.GetString("Clients_Read_Клиент_не_найден_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повреждение не найдено..
        /// </summary>
        internal static string Damages_Read_Повреждение_не_найдено_ {
            get {
                return ResourceManager.GetString("Damages_Read_Повреждение_не_найдено_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такая марка уже есть..
        /// </summary>
        internal static string Marks_AddNew_Такая_марка_уже_есть_ {
            get {
                return ResourceManager.GetString("Marks_AddNew_Такая_марка_уже_есть_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марка не найдена..
        /// </summary>
        internal static string Marks_Read_Марка_не_найдена_ {
            get {
                return ResourceManager.GetString("Marks_Read_Марка_не_найдена_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ не найден..
        /// </summary>
        internal static string Orders_Read_Заказ_не_найден_ {
            get {
                return ResourceManager.GetString("Orders_Read_Заказ_не_найден_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автопрокат не найден..
        /// </summary>
        internal static string Prokats_Read_Автопрокат_не_найден_ {
            get {
                return ResourceManager.GetString("Prokats_Read_Автопрокат_не_найден_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость аренды не найдена..
        /// </summary>
        internal static string Rents_Read_Стоимость_аренды_не_найдена_ {
            get {
                return ResourceManager.GetString("Rents_Read_Стоимость_аренды_не_найдена_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такая услуга уже существует..
        /// </summary>
        internal static string Services_AddNew_Такая_услуга_уже_существует_ {
            get {
                return ResourceManager.GetString("Services_AddNew_Такая_услуга_уже_существует_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуга не найдена..
        /// </summary>
        internal static string Services_Read_Услуга_не_найдена_ {
            get {
                return ResourceManager.GetString("Services_Read_Услуга_не_найдена_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон не найден.
        /// </summary>
        internal static string Templates_Read_Шаблон_не_найден {
            get {
                return ResourceManager.GetString("Templates_Read_Шаблон_не_найден", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой пользователь уже существует..
        /// </summary>
        internal static string Users_AddNew_Такой_пользователь_уже_существует_ {
            get {
                return ResourceManager.GetString("Users_AddNew_Такой_пользователь_уже_существует_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден..
        /// </summary>
        internal static string Users_Read_Пользователь_не_найден_ {
            get {
                return ResourceManager.GetString("Users_Read_Пользователь_не_найден_", resourceCulture);
            }
        }
    }
}
