//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtorentovik.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avtorentovik.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите модель и марку автомобиля..
        /// </summary>
        internal static string AddCarForm_Save_Выберите_модель_и_марку_автомобиля_ {
            get {
                return ResourceManager.GetString("AddCarForm_Save_Выберите_модель_и_марку_автомобиля_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите цвет автомобиля.
        /// </summary>
        internal static string AddCarForm_Save_Выберите_цвет_автомобиля {
            get {
                return ResourceManager.GetString("AddCarForm_Save_Выберите_цвет_автомобиля", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать пункт выдачи для авто..
        /// </summary>
        internal static string AddCarForm_Save_Необходимо_выбрать_пункт_выдачи_для_авто_ {
            get {
                return ResourceManager.GetString("AddCarForm_Save_Необходимо_выбрать_пункт_выдачи_для_авто_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите повреждение для редактирования..
        /// </summary>
        internal static string AddCarForm_simpleButtonChangeDamage_Click_Выберите_повреждение_для_редактирования_ {
            get {
                return ResourceManager.GetString("AddCarForm_simpleButtonChangeDamage_Click_Выберите_повреждение_для_редактирования" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите повреждение для удаления..
        /// </summary>
        internal static string AddCarForm_simpleButtonDeleteDamage_Click_Выберите_повреждение_для_удаления_ {
            get {
                return ResourceManager.GetString("AddCarForm_simpleButtonDeleteDamage_Click_Выберите_повреждение_для_удаления_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите стоимость аренды для удаления..
        /// </summary>
        internal static string AddCarForm_simpleButtonDeleteRent_Click_Выберите_стоимость_аренды_для_удаления_ {
            get {
                return ResourceManager.GetString("AddCarForm_simpleButtonDeleteRent_Click_Выберите_стоимость_аренды_для_удаления_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите стоимость аренды для редактирования..
        /// </summary>
        internal static string AddCarForm_simpleButtonEditRent_Click_Выберите_стоимость_аренды_для_редактирования_ {
            get {
                return ResourceManager.GetString("AddCarForm_simpleButtonEditRent_Click_Выберите_стоимость_аренды_для_редактировани" +
                        "я_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите ФИО клиента..
        /// </summary>
        internal static string AddClientForm_simpleButtonSave_Click_Укажите_ФИО_клиента_ {
            get {
                return ResourceManager.GetString("AddClientForm_simpleButtonSave_Click_Укажите_ФИО_клиента_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите повреждение для редактирования..
        /// </summary>
        internal static string CloseOrderForm_simpleButton2_Click_Выберите_повреждение_для_редактирования_ {
            get {
                return ResourceManager.GetString("CloseOrderForm_simpleButton2_Click_Выберите_повреждение_для_редактирования_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите повреждение для удаления..
        /// </summary>
        internal static string CloseOrderForm_simpleButton3_Click_Выберите_повреждение_для_удаления_ {
            get {
                return ResourceManager.GetString("CloseOrderForm_simpleButton3_Click_Выберите_повреждение_для_удаления_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробег при сдаче должен быть больше пробега в начале..
        /// </summary>
        internal static string CloseOrderForm_simpleButtonAccept_Click_Пробег_при_сдаче_должен_быть_больше_пробега_в_начале_ {
            get {
                return ResourceManager.GetString("CloseOrderForm_simpleButtonAccept_Click_Пробег_при_сдаче_должен_быть_больше_пробе" +
                        "га_в_начале_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите деталь..
        /// </summary>
        internal static string DamageForm_simpleButtonSave_Click_Укажите_деталь_ {
            get {
                return ResourceManager.GetString("DamageForm_simpleButtonSave_Click_Укажите_деталь_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        internal static string LoginForm_Login_Внимание {
            get {
                return ResourceManager.GetString("LoginForm_Login_Внимание", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не правильно введен пароль..
        /// </summary>
        internal static string LoginForm_Login_Не_правильно_введен_пароль_ {
            get {
                return ResourceManager.GetString("LoginForm_Login_Не_правильно_введен_пароль_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такого пользователя нет..
        /// </summary>
        internal static string LoginForm_Login_Такого_пользователя_нет_ {
            get {
                return ResourceManager.GetString("LoginForm_Login_Такого_пользователя_нет_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такого пользователя нет. Хотите создать нового?.
        /// </summary>
        internal static string LoginForm_Login_Такого_пользователя_нет__Хотите_создать_нового_ {
            get {
                return ResourceManager.GetString("LoginForm_Login_Такого_пользователя_нет__Хотите_создать_нового_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите автомобили для удаления..
        /// </summary>
        internal static string MainForm_barButtonItemDeleteCars_ItemClick_Выберите_автомобили_для_удаления_ {
            get {
                return ResourceManager.GetString("MainForm_barButtonItemDeleteCars_ItemClick_Выберите_автомобили_для_удаления_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите клиентов для удаления..
        /// </summary>
        internal static string MainForm_barButtonItemDeleteClient_ItemClick_Выберите_клиентов_для_удаления_ {
            get {
                return ResourceManager.GetString("MainForm_barButtonItemDeleteClient_ItemClick_Выберите_клиентов_для_удаления_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите клиента для редактирования..
        /// </summary>
        internal static string MainForm_barButtonItemEditClient_ItemClick_Выберите_клиента_для_редактирования_ {
            get {
                return ResourceManager.GetString("MainForm_barButtonItemEditClient_ItemClick_Выберите_клиента_для_редактирования_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите машину для редактирования..
        /// </summary>
        internal static string MainForm_Р_Выберите_машину_для_редактирования_ {
            get {
                return ResourceManager.GetString("MainForm_Р_Выберите_машину_для_редактирования_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New_Bitmap_Image {
            get {
                object obj = ResourceManager.GetObject("New_Bitmap_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_icon {
            get {
                object obj = ResourceManager.GetObject("settings_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_icon_small {
            get {
                object obj = ResourceManager.GetObject("settings_icon_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка во время создания пользователя..
        /// </summary>
        internal static string UserForm_simpleButton2_Click_Ошибка_во_время_создания_пользователя_ {
            get {
                return ResourceManager.GetString("UserForm_simpleButton2_Click_Ошибка_во_время_создания_пользователя_", resourceCulture);
            }
        }
    }
}
