//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Avtorentovik.Core.DB
{

    public partial class Cars : PersistentBase
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        CarModels fModel;
        [Association(@"CarReferencesModels")]
        public CarModels Model
        {
            get { return fModel; }
            set { SetPropertyValue<CarModels>("Model", ref fModel, value); }
        }
        int fBody;
        public int Body
        {
            get { return fBody; }
            set { SetPropertyValue<int>("Body", ref fBody, value); }
        }
        bool fKpp;
        public bool Kpp
        {
            get { return fKpp; }
            set { SetPropertyValue<bool>("Kpp", ref fKpp, value); }
        }
        int fColor;
        public int Color
        {
            get { return fColor; }
            set { SetPropertyValue<int>("Color", ref fColor, value); }
        }
        string fNumber;
        public string Number
        {
            get { return fNumber; }
            set { SetPropertyValue<string>("Number", ref fNumber, value); }
        }
        string fSts;
        public string Sts
        {
            get { return fSts; }
            set { SetPropertyValue<string>("Sts", ref fSts, value); }
        }
        int fYear;
        public int Year
        {
            get { return fYear; }
            set { SetPropertyValue<int>("Year", ref fYear, value); }
        }
        string fEngine;
        public string Engine
        {
            get { return fEngine; }
            set { SetPropertyValue<string>("Engine", ref fEngine, value); }
        }
        string fBodyNumber;
        public string BodyNumber
        {
            get { return fBodyNumber; }
            set { SetPropertyValue<string>("BodyNumber", ref fBodyNumber, value); }
        }
        DateTime fInsurance;
        public DateTime Insurance
        {
            get { return fInsurance; }
            set { SetPropertyValue<DateTime>("Insurance", ref fInsurance, value); }
        }
        string fTO;
        public string TO
        {
            get { return fTO; }
            set { SetPropertyValue<string>("TO", ref fTO, value); }
        }
        double fMileage;
        public double Mileage
        {
            get { return fMileage; }
            set { SetPropertyValue<double>("Mileage", ref fMileage, value); }
        }
        Users fUser;
        [Association(@"CarsReferencesUsers")]
        public Users User
        {
            get { return fUser; }
            set { SetPropertyValue<Users>("User", ref fUser, value); }
        }
        int fSiteId;
        public int SiteId
        {
            get { return fSiteId; }
            set { SetPropertyValue<int>("SiteId", ref fSiteId, value); }
        }
        CarRentals fCarRental;
        [Association(@"CarsReferencesCarRentals")]
        public CarRentals CarRental
        {
            get { return fCarRental; }
            set { SetPropertyValue<CarRentals>("CarRental", ref fCarRental, value); }
        }
        bool fDeleted;
        public bool Deleted
        {
            get { return fDeleted; }
            set { SetPropertyValue<bool>("Deleted", ref fDeleted, value); }
        }
        [Association(@"DamagesReferencesCars", typeof(Damages))]
        public IList<Damages> DamagesCollection { get { return GetList<Damages>("DamagesCollection"); } }
        [Association(@"RentsReferencesCars", typeof(Rents))]
        public IList<Rents> RentsCollection { get { return GetList<Rents>("RentsCollection"); } }
        [Association(@"OrdersReferencesCars", typeof(Orders))]
        public IList<Orders> OrdersCollection { get { return GetList<Orders>("OrdersCollection"); } }
    }

}
