//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Avtorentovik.Core.DB
{

    public partial class Clients : PersistentBase
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fFio;
        public string Fio
        {
            get { return fFio; }
            set { SetPropertyValue<string>("Fio", ref fFio, value); }
        }
        string fPhone;
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>("Phone", ref fPhone, value); }
        }
        string fPassport;
        public string Passport
        {
            get { return fPassport; }
            set { SetPropertyValue<string>("Passport", ref fPassport, value); }
        }
        DateTime fWhen;
        public DateTime When
        {
            get { return fWhen; }
            set { SetPropertyValue<DateTime>("When", ref fWhen, value); }
        }
        string fWho;
        public string Who
        {
            get { return fWho; }
            set { SetPropertyValue<string>("Who", ref fWho, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>("Code", ref fCode, value); }
        }
        string fLicense;
        public string License
        {
            get { return fLicense; }
            set { SetPropertyValue<string>("License", ref fLicense, value); }
        }
        DateTime fLicenseDate;
        public DateTime LicenseDate
        {
            get { return fLicenseDate; }
            set { SetPropertyValue<DateTime>("LicenseDate", ref fLicenseDate, value); }
        }
        string fRegistration;
        public string Registration
        {
            get { return fRegistration; }
            set { SetPropertyValue<string>("Registration", ref fRegistration, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>("Address", ref fAddress, value); }
        }
        string fBorn;
        public string Born
        {
            get { return fBorn; }
            set { SetPropertyValue<string>("Born", ref fBorn, value); }
        }
        string fComments;
        public string Comments
        {
            get { return fComments; }
            set { SetPropertyValue<string>("Comments", ref fComments, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>("Status", ref fStatus, value); }
        }
        Users fUser;
        [Association(@"ClientsReferencesUsers")]
        public Users User
        {
            get { return fUser; }
            set { SetPropertyValue<Users>("User", ref fUser, value); }
        }
        int fSiteId;
        public int SiteId
        {
            get { return fSiteId; }
            set { SetPropertyValue<int>("SiteId", ref fSiteId, value); }
        }
        bool fDeleted;
        public bool Deleted
        {
            get { return fDeleted; }
            set { SetPropertyValue<bool>("Deleted", ref fDeleted, value); }
        }
        [Association(@"OrdersReferencesClients", typeof(Orders))]
        public IList<Orders> OrdersCollection { get { return GetList<Orders>("OrdersCollection"); } }
    }

}
