//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Avtorentovik.Core.DB
{

    public partial class Damages : PersistentBase
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fDetail;
        public string Detail
        {
            get { return fDetail; }
            set { SetPropertyValue<string>("Detail", ref fDetail, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        Cars fCar;
        [Association(@"DamagesReferencesCars")]
        public Cars Car
        {
            get { return fCar; }
            set { SetPropertyValue<Cars>("Car", ref fCar, value); }
        }
        bool fArchive;
        public bool Archive
        {
            get { return fArchive; }
            set { SetPropertyValue<bool>("Archive", ref fArchive, value); }
        }
        [Association(@"OrderDamagesReferencesDamages", typeof(OrderDamages))]
        public IList<OrderDamages> OrderDamagesCollection { get { return GetList<OrderDamages>("OrderDamagesCollection"); } }
    }

}
