//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Avtorentovik.Core.DB
{

    public partial class CarModels : PersistentBase
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        Marks fMark;
        [Association(@"ModelsReferencesMarks")]
        public Marks Mark
        {
            get { return fMark; }
            set { SetPropertyValue<Marks>("Mark", ref fMark, value); }
        }
        [Association(@"CarReferencesModels", typeof(Cars))]
        public IList<Cars> Cars { get { return GetList<Cars>("Cars"); } }
    }

}
