//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Avtorentovik.Core.DB
{

    public partial class OrderDamages : PersistentBase
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        Damages fDamage;
        [Association(@"OrderDamagesReferencesDamages")]
        public Damages Damage
        {
            get { return fDamage; }
            set { SetPropertyValue<Damages>("Damage", ref fDamage, value); }
        }
        Orders fOrder;
        [Association(@"OrderDamagesReferencesOrders")]
        public Orders Order
        {
            get { return fOrder; }
            set { SetPropertyValue<Orders>("Order", ref fOrder, value); }
        }
    }

}
