//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Avtorentovik.Core.DB
{

    public partial class Prokats : PersistentBase
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>("Address", ref fAddress, value); }
        }
        string fPhones;
        public string Phones
        {
            get { return fPhones; }
            set { SetPropertyValue<string>("Phones", ref fPhones, value); }
        }
        string fWorktime;
        public string Worktime
        {
            get { return fWorktime; }
            set { SetPropertyValue<string>("Worktime", ref fWorktime, value); }
        }
        Users fUser;
        [Association(@"ProkatsReferencesUsers")]
        public Users User
        {
            get { return fUser; }
            set { SetPropertyValue<Users>("User", ref fUser, value); }
        }
    }

}
