//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Avtorentovik.Core.DB
{

    public partial class Templates : PersistentBase
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fPath;
        public string Path
        {
            get { return fPath; }
            set { SetPropertyValue<string>("Path", ref fPath, value); }
        }
        byte[] fFile;
        public byte[] File
        {
            get { return fFile; }
            set { SetPropertyValue<byte[]>("File", ref fFile, value); }
        }
        Users fUser;
        [Association(@"TemplatesReferencesUsers")]
        public Users User
        {
            get { return fUser; }
            set { SetPropertyValue<Users>("User", ref fUser, value); }
        }
    }

}
