//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Avtorentovik.Core.DB
{

    public partial class Users : PersistentBase
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fLogin;
        public string Login
        {
            get { return fLogin; }
            set { SetPropertyValue<string>("Login", ref fLogin, value); }
        }
        string fPasswordHash;
        public string PasswordHash
        {
            get { return fPasswordHash; }
            set { SetPropertyValue<string>("PasswordHash", ref fPasswordHash, value); }
        }
        int fSiteId;
        public int SiteId
        {
            get { return fSiteId; }
            set { SetPropertyValue<int>("SiteId", ref fSiteId, value); }
        }
        [Association(@"TemplatesReferencesUsers", typeof(Templates))]
        public IList<Templates> TemplatesCollection { get { return GetList<Templates>("TemplatesCollection"); } }
        [Association(@"ProkatsReferencesUsers", typeof(Prokats))]
        public IList<Prokats> ProkatsCollection { get { return GetList<Prokats>("ProkatsCollection"); } }
        [Association(@"RentsReferencesUsers", typeof(Rents))]
        public IList<Rents> RentsCollection { get { return GetList<Rents>("RentsCollection"); } }
        [Association(@"CarsReferencesUsers", typeof(Cars))]
        public IList<Cars> CarsCollection { get { return GetList<Cars>("CarsCollection"); } }
        [Association(@"OrdersReferencesUsers", typeof(Orders))]
        public IList<Orders> OrdersCollection { get { return GetList<Orders>("OrdersCollection"); } }
        [Association(@"ServicesReferencesUsers", typeof(Services))]
        public IList<Services> ServicesCollection { get { return GetList<Services>("ServicesCollection"); } }
        [Association(@"ClientsReferencesUsers", typeof(Clients))]
        public IList<Clients> ClientsCollection { get { return GetList<Clients>("ClientsCollection"); } }
    }

}
